app/controllers/SiteController.php
<?php

/**
 * SiteController class
 * @author Pascal Brewing <pascalbrewing@gmail.com>
 * @link http://www.pascal-brewing.de
 * @license http://www.opensource.org/licenses/bsd-license.php New BSD License
 */
class SiteController extends EController
{

    /**
     * @return array action filters
     */
    public function filters()
    {
        return array(
            'accessControl', // perform access control for CRUD operations
            'postOnly + delete', // we only allow deletion via POST request
        );
    }

    /**
     * Specifies the access control rules.
     * This method is used by the 'accessControl' filter.
     * @return array access control rules
     */
    public function accessRules()
    {
        return array(
            array('allow', // allow all users to perform 'index' and 'view' actions
                'actions' => array('index', 'css', 'ajaxTest', 'doc', 'error', 'components', 'javascript'),
                'users' => array('*'),
            ),
            array('deny', // deny all users
                'users' => array('*'),
            ),
        );
    }

    public function actionIndex()
    {
//        $this->redirect('site/css');
        $this->render('home');
    }

    public function actionCss()
    {
        $model = new User();
        $this->layout = '//layouts/column_2';

        if (isset($_POST['User'])) {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
        $this->render('css', array('model' => $model));
    }

    public function actionComponents()
    {
        $model = new User();
        $this->layout = '//layouts/column_2';

        if (isset($_POST['User'])) {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
        $this->render('components', array('model' => $model));
    }

    public function actionJavascript()
    {
        $model = new User();
        $this->layout = '//layouts/column_2';

        if (isset($_POST['User'])) {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }
        $this->render('javascript', array('model' => $model));
    }

    /**
     * Ajax Sample
     */
    public function actionAjaxTest()
    {
        $message = $_POST['message'];
        echo BsHtml::alert(BsHtml::ALERT_COLOR_INFO, "<strong>Message:</strong>{$message}");
        Yii::app()->end();
    }

    /**
     * Apigen Documentation
     * php apigen.php apigen --source bootstrap/app/lib/vendor/drmabuse/yii-bootstrap-3-module/ --destination bootstrap/www/class_reference
     */
    public function actionDoc()
    {
        $this->render('documentation');
    }

    /**
     * This is the action to handle external exceptions.
     */
    public function actionError()
    {
        if ($error = Yii::app()->errorHandler->error) {
            if (Yii::app()->request->isAjaxRequest)
                echo $error['message'];
            else
                $this->render('error', $error);
        }
    }

    /**
     * Displays the contact page
     */
    public function actionContact()
    {
        $model = new ContactForm;
        if (isset($_POST['ContactForm'])) {
            $model->attributes = $_POST['ContactForm'];
            if ($model->validate()) {
                $headers = "From: {$model->email}\r\nReply-To: {$model->email}";
                mail(Yii::app()->params['adminEmail'], $model->subject, $model->body, $headers);
                Yii::app()->user->setFlash('contact', 'Thank you for contacting us. We will respond to you as soon as possible.');
                $this->refresh();
            }
        }
        $this->render('contact', array('model' => $model));
    }

    /**
     * Displays the login page
     */
    public function actionLogin()
    {
        if (!defined('CRYPT_BLOWFISH') || !CRYPT_BLOWFISH)
            throw new CHttpException(500, "This application requires that PHP was compiled with Blowfish support for crypt().");

        $model = new LoginForm;

        // if it is ajax validation request
        if (isset($_POST['ajax']) && $_POST['ajax'] === 'login-form') {
            echo CActiveForm::validate($model);
            Yii::app()->end();
        }

        // collect user input data
        if (isset($_POST['LoginForm'])) {
            $model->attributes = $_POST['LoginForm'];
            // validate user input and redirect to the previous page if valid
            if ($model->validate() && $model->login())
                $this->redirect(Yii::app()->user->returnUrl);
        }
        // display the login form
        $this->render('login', array('model' => $model));
    }

    public function actionRegister()
    {

    }
    /**
     * Logs out the current user and redirect to homepage.
     */
    public function actionLogout()
    {
        Yii::app()->user->logout();
        $this->redirect(Yii::app()->homeUrl);
    }
}

app/views/layouts/column_2.php
<?php $this->beginContent('//layouts/main'); ?>
<div class="row">
    <div class="col-md-3">
        <?php $this->renderPartial('//layouts_column_2/sidebar') ?>
    </div>
    <div id="mainCol" class="col-md-9">
        <?php echo $content ?>
    </div>
</div>
<?php $this->endContent(); ?>

app/views/layouts/main.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="author" content="Pascal Brewing">
    <meta name="keywords" content="Yii,Bootstrap3,Widgets,Composer,Grunt">
    <link rel="shortcut icon" href="../../assets/ico/favicon.png">
    <title><?= $this->pageTitle ?> | Yii-Bootstrap-3-Module</title>
    <?php $this->renderPartial('//script_header') ?>
</head>
<body>

<div id="wrap">
    <!-- Fixed navbar -->
    <?php $this->renderPartial('//layouts/navbar') ?>
    <!-- Begin page content -->
    <div class="container">
        <?php echo $content ?>
    </div>
</div>


<div id="demo_modal" class="modal fade">
    <div class="modal-dialog">
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                <h4 class="modal-title">Modal title</h4>
            </div>
            <div class="modal-body">
                <p></p>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                <button type="button" class="btn btn-primary">Save changes</button>
            </div>
        </div>
        <!-- /.modal-content -->
    </div>
    <!-- /.modal-dialog -->
</div><!-- /.modal -->
<div class="clearfix"></div>
</body>
</html>

app/views/layouts/navbar.php
<?php
function isActive($url){
    if(Yii::app()->request->url === $url){
        return true;
    }
    return false;
}
$urls = [
    [
      'label' => 'CSS',
      'url'   => Yii::app()->baseUrl.'/site/css',
      'active'=> isActive(Yii::app()->baseUrl.'/site/css')
    ],
    [
      'label' => 'Components',
      'url'   => Yii::app()->baseUrl.'/site/components',
      'active'=> isActive(Yii::app()->baseUrl.'/site/components')
    ],
    [
      'label' => 'Javascript',
      'url'   => Yii::app()->baseUrl.'/site/javascript',
      'active'=> isActive(Yii::app()->baseUrl.'/site/javascript')
    ],
    [
      'label' => 'Class Reference',
      'url'   => Yii::app()->baseUrl.'/doc',
      'active'=> isActive(Yii::app()->baseUrl.'/doc')
    ],
    [
        'label'         => CHtml::image(Yii::app()->baseUrl.'/img/bootstrap.png','Bootstrap3 ;)',array('class' => '','height' => 20)),
        'linkOptions'   => ['target' => '_blank'],
        'url'           => 'http://getbootstrap.com',
    ],
    [
        'label'         => CHtml::image(Yii::app()->baseUrl.'/img/yii.png','Yii ;)',array('class' => '','height' => 20)),
        'linkOptions'   => ['target' => '_blank'],
        'url'           => 'http://www.yiiframework.com/extension/yii-bootstrap3-module/',
    ],
    [
        'label'         => CHtml::image(Yii::app()->baseUrl.'/img/bitbucket_logo_landing.png','Bitbucket ;)',array('class' => '','height' => 20)),
        'linkOptions'   => ['target' => '_blank'],
        'url'           => 'https://bitbucket.org/DrMabuse/yii-bootstrap-3-module',
    ],
    [
        'label'         => CHtml::image(Yii::app()->baseUrl.'/img/logo.png','Packagist ;)',array('class' => '','height' => 20)),
        'linkOptions'   => ['target' => '_blank'],
        'url'           => 'https://packagist.org/packages/drmabuse/yii-bootstrap-3-module'

    ]
];
?>
<header class="navbar navbar-inverse navbar-fixed-top bs-docs-nav" role="banner">
    <div class="container">
        <div class="navbar-header">
            <button class="navbar-toggle" type="button" data-toggle="collapse" data-target=".bs-navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a href="../" class="navbar-brand">Yii Bootstrap3 Extension</a>
        </div>
        <nav class="collapse navbar-collapse bs-navbar-collapse" role="navigation">
            <?php
            $this->widget('zii.widgets.CMenu', array(
                'items'         => $urls,
                'encodeLabel'  => false,
                'htmlOptions'   => [
                    'class' => 'nav navbar-nav'
                ]
            ));
            ?>
        </nav>
    </div>
</header>

app/views/layouts/ol_header.php
<div class="navbar navbar-default navbar-fixed-top">
    <div class="container ">
        <ul class=" nav navbar-nav hidden-xs hidden-sm">
            <li>
                <a href="<?php echo  Yii::app()->createAbsoluteUrl('/') ?>">
                    <h1 style="margin-top: 0">Yii <small>Bootstrap-3-Module</small></h1>
                </a>
            </li>
            <li class=" ">
                <?php echo BsHtml::link(
                    CHtml::image(
                        Yii::app()->baseUrl.'/img/bootstrap.png',
                        'Bootstrap3 ;)',
                        array(
                            'class' => '',
                            'height' => 30
                        )
                    ),
                    'http://getbootstrap.com',
                    array(
                        'target' => '_blank',
                    )
                )
                ?>
                <?php echo BsHtml::link(
                    CHtml::image(
                        Yii::app()->baseUrl.'/img/yii.png',
                        'Yii ;)',
                        array(
                            'class' => '',
                            'height' => 30
                        )
                    ),
                    'http://www.yiiframework.com/extension/yii-bootstrap3-module/',
                    array(
                        'target' => '_blank',
                    )
                )
                ?>
            </li>
            <li class="">
                <?php echo BsHtml::link(
                    CHtml::image(
                        Yii::app()->baseUrl.'/img/bitbucket_logo_landing.png',
                        'Bitbucket ;)',
                        array(
                            'class' => '',
                            'height' => 30
                        )
                    ),
                    'https://bitbucket.org/DrMabuse/yii-bootstrap-3-module',
                    array(
                        'target' => '_blank',
                    )
                )
                ?>
            </li>
            <li class="">
                <?php echo BsHtml::link(
                    CHtml::image(
                        Yii::app()->baseUrl.'/img/logo.png',
                        'Packagist ;)',
                        array(
                            'class' => '',
                            'height' => 30
                        )
                    ),
                    'https://packagist.org/packages/drmabuse/yii-bootstrap-3-module',
                    array(
                        'target' => '_blank',
                    )
                )
                ?>
            </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">
            <li>
                <?php echo BsHtml::link(BsHtml::icon(BsHtml::GLYPHICON_BOOKMARK).' Class Reference','doc',array('style' => 'font-size:16px;margin-top:20px;')) ?>
            </li>
            <!--                    <li class="dropdown">-->
            <!--                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Dropdown <b class="caret"></b></a>-->
            <!--                        <ul class="dropdown-menu">-->
            <!--                            <li><a href="#">Action</a></li>-->
            <!--                            <li><a href="#">Another action</a></li>-->
            <!--                            <li><a href="#">Something else here</a></li>-->
            <!--                            <li><a href="#">Separated link</a></li>-->
            <!--                        </ul>-->
            <!--                    </li>-->
        </ul>
    </div>
</div>